server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
         - id: api_route
           uri: https://localhost:8123
           predicates:
             - Path=/api/{api_url}
           filters:
             - AddRequestHeader=X-Request-red, blue
      default-filters:
        - AddResponseHeader=source, su
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: zk-registry
    address: zookeeper://127.0.0.1:21810
  config-center:
    address: zookeeper://127.0.0.1:21810
  metadata-report:
    address: zookeeper://127.0.0.1:21810